src/AdminBundle/Form/Type/FileArrayType.php
<?php

namespace AdminBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class FileArrayType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'entry_options' => array('label' => false),
            'allow_add' => true,
            'allow_delete' => true,
            'by_reference' => false
        ));
    }

    public function getParent()
    {
        return CollectionType::class;
    }
}

src/AdminBundle/Resources/views/Field/CustomFields/file_widget.html.twig
{% block file_widget %} TESTEST
    {% spaceless %}
        {% set type = type|default('file') %}
        {% set subject =  form.parent.vars.value %}
        {% if subject and subject.id and "Pdf" in _context.id %}
            <a href="{{ vich_uploader_asset(subject, "file") }}">{{subject.fileName}}</a>
        {% else %}
            <input class="imgUpload" type="{{ type }}" {{ block('widget_attributes') }} />
            {% if subject and subject.id and attribute(_context.subject, name|replace({ ('File'): 'Name' })) is defined  %}
                <img src="{{ asset(vich_uploader_asset(subject, name)) }}" width="200" />
            {% endif %}
        {% endif %}
    {% endspaceless %}
{% endblock %}

src/AdminBundle/Resources/views/Field/CustomFields/imagefile_widget.html.twig
{% block _form_logoFile_widget %}
    {{ block('image_widgetfield') }}
{% endblock %}
{% block _form_photoFile_widget %}
    {{ block('image_widgetfield') }}
{% endblock %}

{% block image_widgetfield %} TESTEST
    {% spaceless %}
    <div class="file-wrapper {% if form.vars.attr['class'] is defined %}{{form.vars.attr['class']}}{% endif %}">
        {% set type = type|default('file') %}
        <input class="imgUpload" type="{{ type }}" {{ block('widget_attributes') }} />
        <label class="w100" for="{{form.vars.id}}">Télécharger</label>
        {% set subject = form.parent.vars.value %}
        {# {{dump(form.parent.vars.value) }}; #}
        {% if subject and subject.id and subject.logoName %}
            <img src="{{ asset(vich_uploader_asset(subject, name)) }}" width="200" />
        {% endif %}
    </div>
    {% endspaceless %}
{% endblock %}